### ISSUE TITLE
H3 style

### ISSUE THREAD

**Issue by johngriffin** [atchai/atchai-hugo#3]
Since we made <a> Raleway-regular, H3's containing links have mixed fonts - see attachment.

To solve this please make H3 use Raleway-regular, not semibold.  Also, I think that <a> should not have a definition for font-face, it should just inherit.

**Comment by johngriffin** [comment]
<img width="813" alt="screen shot 2016-04-20 at 17 10 48" src="https://cloud.githubusercontent.com/assets/273591/14681946/370944e4-071b-11e6-9ec3-32b6fa375905.png">

**Comment by nanuclickity** [comment]
fixed in d7622c346e964bdaa68e28ad799b50f8a517858f
will be merged with PR #2
